sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ashukruti/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ashukruti/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "dockerreact"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-703765498544"
  bucket_path: "dockerreact"
on:
  branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_key: "$AWS_SECRET_KEY"




